/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ceklowongan;
import java.awt.Checkbox;
import javax.swing.JOptionPane; 



 

/**
 *
 * @author nadia
 */
public class proloker extends javax.swing.JFrame {
    { Checkbox ak = new Checkbox ("AKUTANSI");
        Checkbox ap = new Checkbox ("AUDIT PAJAK");
        Checkbox sek = new Checkbox ("SEKRETARIS");
        Checkbox sd = new Checkbox ("SOFTWARE DEVELOPER");
        Checkbox sa= new Checkbox ("SYSTEM ANALYST");
        Checkbox is = new Checkbox ("IT SUPPORT");
        Checkbox adm = new Checkbox ("ADMINISTRATOR");
        Checkbox or = new Checkbox ("LAINNYA*");
        
    
    }
    /**
     * Creates new form proloker
     */
    public proloker() {
        initComponents();
        
    }

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NM = new javax.swing.JTextField();
        TTL = new javax.swing.JTextField();
        dp = new javax.swing.JTextField();
        t = new javax.swing.JComboBox<>();
        b = new javax.swing.JComboBox<>();
        th = new javax.swing.JComboBox<>();
        PT = new javax.swing.JTextField();
        JUR = new javax.swing.JComboBox<>();
        a = new javax.swing.JRadioButton();
        aa = new javax.swing.JRadioButton();
        aaa = new javax.swing.JRadioButton();
        ap = new java.awt.Checkbox();
        ak = new java.awt.Checkbox();
        adm = new java.awt.Checkbox();
        sek = new java.awt.Checkbox();
        sd = new java.awt.Checkbox();
        sa = new java.awt.Checkbox();
        is = new java.awt.Checkbox();
        or = new java.awt.Checkbox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        out = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOWONGAN PEKERJAAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 110, 449, 42);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(15, 310, 74, 28);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TEMPAT TANGGAL LAHIR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(15, 365, 309, 28);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PENDIDIKAN TERAKHIR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(15, 421, 288, 28);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JURUSAN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(15, 468, 110, 28);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("POSISI YANG ANDA INGINKAN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(15, 637, 356, 28);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DOMISILI PERUSAHAAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(15, 793, 286, 28);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GAJI YANG ANDA INGINKAN");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(15, 848, 334, 28);

        NM.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NM.setText(" ");
        getContentPane().add(NM);
        NM.setBounds(478, 312, 358, 26);

        TTL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TTL.setText(" ");
        getContentPane().add(TTL);
        TTL.setBounds(478, 366, 170, 26);

        dp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dp.setText(" ");
        getContentPane().add(dp);
        dp.setBounds(478, 796, 358, 26);

        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t);
        t.setBounds(670, 370, 70, 26);

        b.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(b);
        b.setBounds(750, 370, 110, 26);

        th.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(th);
        th.setBounds(880, 370, 90, 26);

        PT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PT.setText(" ");
        getContentPane().add(PT);
        PT.setBounds(478, 424, 358, 26);

        JUR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        JUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JURActionPerformed(evt);
            }
        });
        getContentPane().add(JUR);
        JUR.setBounds(478, 471, 241, 26);

        buttonGroup1.add(a);
        a.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        a.setText("1-5 JUTA/BULAN");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(478, 845, 175, 31);

        buttonGroup1.add(aa);
        aa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        aa.setText("5-10 JUTA/BULAN");
        aa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaActionPerformed(evt);
            }
        });
        getContentPane().add(aa);
        aa.setBounds(666, 845, 190, 31);

        buttonGroup1.add(aaa);
        aaa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        aaa.setText(">10 JUTA/BULAN");
        aaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaaActionPerformed(evt);
            }
        });
        getContentPane().add(aaa);
        aaa.setBounds(863, 845, 179, 31);

        ap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ap.setLabel("AUDIT PAJAK\n");
        getContentPane().add(ap);
        ap.setBounds(478, 637, 147, 28);

        ak.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ak.setLabel("AKUTANSI\n");
        getContentPane().add(ak);
        ak.setBounds(478, 675, 119, 28);

        adm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adm.setLabel("ADMINISTRATOR");
        getContentPane().add(adm);
        adm.setBounds(478, 751, 177, 28);

        sek.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sek.setLabel("SEKRETARIS");
        getContentPane().add(sek);
        sek.setBounds(478, 713, 142, 28);

        sd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sd.setLabel("SOFTWARE DEVELOPER");
        getContentPane().add(sd);
        sd.setBounds(695, 713, 246, 28);

        sa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sa.setLabel("SYSTEM ANALYST");
        getContentPane().add(sa);
        sa.setBounds(695, 637, 192, 28);

        is.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        is.setLabel("IT SUPPORT");
        getContentPane().add(is);
        is.setBounds(695, 675, 134, 28);

        or.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        or.setLabel("LAINNYA*");
        getContentPane().add(or);
        or.setBounds(695, 751, 114, 28);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("NEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 910, 100, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("PROSES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 910, 190, 37);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("APPLY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(840, 910, 160, 37);

        out.setColumns(20);
        out.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        out.setRows(5);
        jScrollPane1.setViewportView(out);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1087, 312, 662, 577);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 910, 160, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ceklowongan/bac.jpg"))); // NOI18N
        jLabel10.setText(" ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -20, 1900, 1090);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"DATA ANDA TELAH DISIMPAN");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        a.isSelected();
    }//GEN-LAST:event_aActionPerformed

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
        // TODO add your handling code here:
        aa.isSelected();
    }//GEN-LAST:event_aaActionPerformed

    private void aaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaaActionPerformed
        // TODO add your handling code here:
        aaa.isSelected();
    }//GEN-LAST:event_aaaActionPerformed

    private void JURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JURActionPerformed
if (JUR.getSelectedItem()=="PILIH"){

ak.setEnabled(true);

ap.setEnabled(true);

adm.setEnabled(true);

sek.setEnabled(true);

sd.setEnabled(true);

sa.setEnabled(true);

is.setEnabled(true);

or.setEnabled(true);

}else if (JUR.getSelectedItem()=="AKUTANSI/PERPAJAKAN"){

ak.setEnabled(true);

ap.setEnabled(true);

adm.setEnabled(false);

sek.setEnabled(false);

sd.setEnabled(false);

sa.setEnabled(false);

is.setEnabled(false);

or.setEnabled(false);

}else if (JUR.getSelectedItem()=="ADMINISTRASI"){

ak.setEnabled(false);

ap.setEnabled(false);

adm.setEnabled(true);

sek.setEnabled(true);

sd.setEnabled(false);

sa.setEnabled(false);

is.setEnabled(false);

or.setEnabled(false);

}else if (JUR.getSelectedItem()=="TEKNIK INFORMASI/SISTEM INFORMASI"){

ak.setEnabled(false);

ap.setEnabled(false);

adm.setEnabled(false);

sek.setEnabled(false);

sd.setEnabled(true);

sa.setEnabled(true);

is.setEnabled(true);

or.setEnabled(false);

}else{

ak.setEnabled(false);

ap.setEnabled(false);

adm.setEnabled(false);

sek.setEnabled(false);

sd.setEnabled(false);

sa.setEnabled(false);

is.setEnabled(false);

or.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_JURActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        {
if (ak.getState()){
    out.setText("PT. ADIL JAYA, Jl. SUDIRMAN"
+"\n"+ "Membutuhkan Pegawai yang rajin, jujur, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadia@yahoo.com"+"\n\n"+""
+ "PT. KARYA JAYA, Jl. A.YANI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yaya@yahoo.com"+"\n\n"+""
+"PT. AEGIS JAYA, Jl. TEMBALANG"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ayun@yahoo.com"+"\n\n"+""
+ "PT. HUTAMA, Jl. MELATI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yudha@yahoo.com"+"\n\n"+""
+ "PT. TEKKOM19 , Jl. MAWAR "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : saputra@yahoo.com"+"\n\n"+""
+ "PT. JAYA ABADI , Jl. A.R.HAKIM"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ "terampil"+"\n"+"E-Mail : abdul@yahoo.com"+"\n\n"+""
+ "PT. DAMAI JAYA, Jl. JEND.SUDIRMAN 1"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : galih@yahoo.com"+"\n\n"+""
+ "PT. AULIADEEN, Jl. MELATI 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : iqbal@yahoo.com"+"\n\n"+""
+ "PT.CHROMEUP, Jl. MELATI 4"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : rani@yahoo.com"+"\n\n"+""
+ "PT. MAJU TERUS, Jl. HAKIM A.R"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : bagus@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI BARU, Jl. ANGGREK"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : kevin@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI JAYA, Jl. APEL "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : alle@yahoo.com"+"\n\n"+""
+ "PT. INDUSTRINDO, Jl. JATIMULYA"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : azaliaa@yahoo.com"+"\n\n"+""
+ "PT. VAMOS, Jl. GATOT SUBROTO"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ella@yahoo.com"+"\n\n"+""
+ "PT. GUNTUR GROUP, Jl. MANGGA 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadiasanath@yahoo.com"+"\n\n");
 
}
if(ap.getState()){
out.setText("PT. ADIL JAYA, Jl. SUDIRMAN"
+"\n"+ "Membutuhkan Pegawai yang rajin, jujur, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadia@yahoo.com"+"\n\n"+""
+ "PT. KARYA JAYA, Jl. A.YANI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yaya@yahoo.com"+"\n\n"+""
+"PT. AEGIS JAYA, Jl. TEMBALANG"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ayun@yahoo.com"+"\n\n"+""
+ "PT. HUTAMA, Jl. MELATI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yudha@yahoo.com"+"\n\n"+""
+ "PT. TEKKOM19 , Jl. MAWAR "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : saputra@yahoo.com"+"\n\n"+""
+ "PT. JAYA ABADI , Jl. A.R.HAKIM"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ "terampil"+"\n"+"E-Mail : abdul@yahoo.com"+"\n\n"+""
+ "PT. DAMAI JAYA, Jl. JEND.SUDIRMAN 1"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : galih@yahoo.com"+"\n\n"+""
+ "PT. AULIADEEN, Jl. MELATI 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : iqbal@yahoo.com"+"\n\n"+""
+ "PT.CHROMEUP, Jl. MELATI 4"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : rani@yahoo.com"+"\n\n"+""
+ "PT. MAJU TERUS, Jl. HAKIM A.R"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : bagus@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI BARU, Jl. ANGGREK"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : kevin@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI JAYA, Jl. APEL "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : alle@yahoo.com"+"\n\n"+""
+ "PT. INDUSTRINDO, Jl. JATIMULYA"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : azaliaa@yahoo.com"+"\n\n"+""
+ "PT. VAMOS, Jl. GATOT SUBROTO"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ella@yahoo.com"+"\n\n"+""
+ "PT. GUNTUR GROUP, Jl. MANGGA 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadiasanath@yahoo.com"+"\n\n");
}
if(sek.getState()){
out.setText("PT. ADIL JAYA, Jl. SUDIRMAN"
+"\n"+ "Membutuhkan Pegawai yang rajin, jujur, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadia@yahoo.com"+"\n\n"+""
+ "PT. KARYA JAYA, Jl. A.YANI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yaya@yahoo.com"+"\n\n"+""
+"PT. AEGIS JAYA, Jl. TEMBALANG"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ayun@yahoo.com"+"\n\n"+""
+ "PT. HUTAMA, Jl. MELATI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yudha@yahoo.com"+"\n\n"+""
+ "PT. TEKKOM19 , Jl. MAWAR "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : saputra@yahoo.com"+"\n\n"+""
+ "PT. JAYA ABADI , Jl. A.R.HAKIM"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ "terampil"+"\n"+"E-Mail : abdul@yahoo.com"+"\n\n"+""
+ "PT. DAMAI JAYA, Jl. JEND.SUDIRMAN 1"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : galih@yahoo.com"+"\n\n"+""
+ "PT. AULIADEEN, Jl. MELATI 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : iqbal@yahoo.com"+"\n\n"+""
+ "PT.CHROMEUP, Jl. MELATI 4"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : rani@yahoo.com"+"\n\n"+""
+ "PT. MAJU TERUS, Jl. HAKIM A.R"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : bagus@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI BARU, Jl. ANGGREK"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : kevin@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI JAYA, Jl. APEL "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : alle@yahoo.com"+"\n\n"+""
+ "PT. INDUSTRINDO, Jl. JATIMULYA"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : azaliaa@yahoo.com"+"\n\n"+""
+ "PT. VAMOS, Jl. GATOT SUBROTO"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ella@yahoo.com"+"\n\n"+""
+ "PT. GUNTUR GROUP, Jl. MANGGA 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadiasanath@yahoo.com"+"\n\n");
}
if(sa.getState()){
out.setText("PT. ADIL JAYA, Jl. SUDIRMAN"
+"\n"+ "Membutuhkan Pegawai yang rajin, jujur, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadia@yahoo.com"+"\n\n"+""
+ "PT. KARYA JAYA, Jl. A.YANI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yaya@yahoo.com"+"\n\n"+""
+"PT. AEGIS JAYA, Jl. TEMBALANG"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ayun@yahoo.com"+"\n\n"+""
+ "PT. HUTAMA, Jl. MELATI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yudha@yahoo.com"+"\n\n"+""
+ "PT. TEKKOM19 , Jl. MAWAR "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : saputra@yahoo.com"+"\n\n"+""
+ "PT. JAYA ABADI , Jl. A.R.HAKIM"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ "terampil"+"\n"+"E-Mail : abdul@yahoo.com"+"\n\n"+""
+ "PT. DAMAI JAYA, Jl. JEND.SUDIRMAN 1"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : galih@yahoo.com"+"\n\n"+""
+ "PT. AULIADEEN, Jl. MELATI 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : iqbal@yahoo.com"+"\n\n"+""
+ "PT.CHROMEUP, Jl. MELATI 4"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : rani@yahoo.com"+"\n\n"+""
+ "PT. MAJU TERUS, Jl. HAKIM A.R"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : bagus@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI BARU, Jl. ANGGREK"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : kevin@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI JAYA, Jl. APEL "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : alle@yahoo.com"+"\n\n"+""
+ "PT. INDUSTRINDO, Jl. JATIMULYA"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : azaliaa@yahoo.com"+"\n\n"+""
+ "PT. VAMOS, Jl. GATOT SUBROTO"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ella@yahoo.com"+"\n\n"+""
+ "PT. GUNTUR GROUP, Jl. MANGGA 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadiasanath@yahoo.com"+"\n\n"); }
if(sd.getState()){
out.setText("PT. ADIL JAYA, Jl. SUDIRMAN"
+"\n"+ "Membutuhkan Pegawai yang rajin, jujur, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadia@yahoo.com"+"\n\n"+""
+ "PT. KARYA JAYA, Jl. A.YANI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yaya@yahoo.com"+"\n\n"+""
+"PT. AEGIS JAYA, Jl. TEMBALANG"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ayun@yahoo.com"+"\n\n"+""
+ "PT. HUTAMA, Jl. MELATI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yudha@yahoo.com"+"\n\n"+""
+ "PT. TEKKOM19 , Jl. MAWAR "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : saputra@yahoo.com"+"\n\n"+""
+ "PT. JAYA ABADI , Jl. A.R.HAKIM"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ "terampil"+"\n"+"E-Mail : abdul@yahoo.com"+"\n\n"+""
+ "PT. DAMAI JAYA, Jl. JEND.SUDIRMAN 1"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : galih@yahoo.com"+"\n\n"+""
+ "PT. AULIADEEN, Jl. MELATI 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : iqbal@yahoo.com"+"\n\n"+""
+ "PT.CHROMEUP, Jl. MELATI 4"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : rani@yahoo.com"+"\n\n"+""
+ "PT. MAJU TERUS, Jl. HAKIM A.R"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : bagus@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI BARU, Jl. ANGGREK"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : kevin@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI JAYA, Jl. APEL "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : alle@yahoo.com"+"\n\n"+""
+ "PT. INDUSTRINDO, Jl. JATIMULYA"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : azaliaa@yahoo.com"+"\n\n"+""
+ "PT. VAMOS, Jl. GATOT SUBROTO"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ella@yahoo.com"+"\n\n"+""
+ "PT. GUNTUR GROUP, Jl. MANGGA 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadiasanath@yahoo.com"+"\n\n"); 
}
if(adm.getState()){
out.setText("PT. ADIL JAYA, Jl. SUDIRMAN"
+"\n"+ "Membutuhkan Pegawai yang rajin, jujur, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadia@yahoo.com"+"\n\n"+""
+ "PT. KARYA JAYA, Jl. A.YANI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yaya@yahoo.com"+"\n\n"+""
+"PT. AEGIS JAYA, Jl. TEMBALANG"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ayun@yahoo.com"+"\n\n"+""
+ "PT. HUTAMA, Jl. MELATI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yudha@yahoo.com"+"\n\n"+""
+ "PT. TEKKOM19 , Jl. MAWAR "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : saputra@yahoo.com"+"\n\n"+""
+ "PT. JAYA ABADI , Jl. A.R.HAKIM"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ "terampil"+"\n"+"E-Mail : abdul@yahoo.com"+"\n\n"+""
+ "PT. DAMAI JAYA, Jl. JEND.SUDIRMAN 1"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : galih@yahoo.com"+"\n\n"+""
+ "PT. AULIADEEN, Jl. MELATI 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : iqbal@yahoo.com"+"\n\n"+""
+ "PT.CHROMEUP, Jl. MELATI 4"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : rani@yahoo.com"+"\n\n"+""
+ "PT. MAJU TERUS, Jl. HAKIM A.R"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : bagus@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI BARU, Jl. ANGGREK"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : kevin@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI JAYA, Jl. APEL "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : alle@yahoo.com"+"\n\n"+""
+ "PT. INDUSTRINDO, Jl. JATIMULYA"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : azaliaa@yahoo.com"+"\n\n"+""
+ "PT. VAMOS, Jl. GATOT SUBROTO"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ella@yahoo.com"+"\n\n"+""
+ "PT. GUNTUR GROUP, Jl. MANGGA 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadiasanath@yahoo.com"+"\n\n"); 
}
    if(is.getState()){
out.setText("PT. ADIL JAYA, Jl. SUDIRMAN"
+"\n"+ "Membutuhkan Pegawai yang rajin, jujur, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadia@yahoo.com"+"\n\n"+""
+ "PT. KARYA JAYA, Jl. A.YANI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yaya@yahoo.com"+"\n\n"+""
+"PT. AEGIS JAYA, Jl. TEMBALANG"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ayun@yahoo.com"+"\n\n"+""
+ "PT. HUTAMA, Jl. MELATI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yudha@yahoo.com"+"\n\n"+""
+ "PT. TEKKOM19 , Jl. MAWAR "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : saputra@yahoo.com"+"\n\n"+""
+ "PT. JAYA ABADI , Jl. A.R.HAKIM"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ "terampil"+"\n"+"E-Mail : abdul@yahoo.com"+"\n\n"+""
+ "PT. DAMAI JAYA, Jl. JEND.SUDIRMAN 1"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : galih@yahoo.com"+"\n\n"+""
+ "PT. AULIADEEN, Jl. MELATI 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : iqbal@yahoo.com"+"\n\n"+""
+ "PT.CHROMEUP, Jl. MELATI 4"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : rani@yahoo.com"+"\n\n"+""
+ "PT. MAJU TERUS, Jl. HAKIM A.R"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : bagus@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI BARU, Jl. ANGGREK"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : kevin@yahoo.com"+"\n\n"+""
+ "PT. MANDIRI JAYA, Jl. APEL "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : alle@yahoo.com"+"\n\n"+""
+ "PT. INDUSTRINDO, Jl. JATIMULYA"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : azaliaa@yahoo.com"+"\n\n"+""
+ "PT. VAMOS, Jl. GATOT SUBROTO"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ella@yahoo.com"+"\n\n"+""
+ "PT. GUNTUR GROUP, Jl. MANGGA 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadiasanath@yahoo.com"+"\n\n");
    
}else if (JUR.getSelectedItem()=="LAINNYA"){
if(or.getState()){
out.setText("PT. MUSTIKA RATU, Jl. SUDIRMAN"
+"\n"+ "Membutuhkan Pegawai yang rajin, jujur, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : nadia@yahoo.com"+"\n\n"+""
+ "PT. NEW VISION, Jl. A.YANI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yaya@yahoo.com"+"\n\n"+""
+"PT. NEVADA, Jl. TEMBALANG"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : ayun@yahoo.com"+"\n\n"+""
+ "PT. KARYA HUTAMA, Jl. MELATI"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : yudha@yahoo.com"+"\n\n"+""
+ "PT. LAZADA , Jl. MAWAR "
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : saputra@yahoo.com"+"\n\n"+""
+ "PT. ABADI JAYA, Jl. A.R.HAKIM"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ "terampil"+"\n"+"E-Mail : abdul@yahoo.com"+"\n\n"+""
+ "PT. VOVA, Jl. JEND.SUDIRMAN 1"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : galih@yahoo.com"+"\n\n"+""
+ "PT. ALADIN, Jl. MELATI 2"
+"\n"+ "Membutuhkan Pegawai yang rajin, bekerja keras dan"
+ " terampil"+"\n"+"E-Mail : iqbal@yahoo.com"+"\n\n");
}}

  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    } 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
NM.setText("");
TTL.setText("");
PT.setText("");
dp.setText("");
out.setText(""); 
a.isSelected();
aa.isSelected();
aaa.isSelected();
JUR.setSelectedIndex(0);
ak.getState();
is.getState();
or.getState();
ak.setEnabled(true);
ap.setEnabled(true);
adm.setEnabled(true);
sek.setEnabled(true);
sd.setEnabled(true);
sa.setEnabled(true);
is.setEnabled(true);
or.setEnabled(true);
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new data().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        JUR.addItem("PILIH");

JUR.addItem("AKUTANSI/PERPAJAKAN");

JUR.addItem("ADMINISTRASI");

JUR.addItem("TEKNIK INFORMASI/SISTEM INFORMASI");

JUR.addItem("LAINNYA");
         t.addItem("PILIH");

for (int i=1;i<=31;i++){

t.addItem(String.valueOf(i));

}

th.addItem("PILIH");

for (int a=1999;a<=2005;a++){

th.addItem(String.valueOf(a));

}

String[] bulan={"PILIH","Januari","Februari","Maret","April","Mei","Juni",

"Juli","Agustus","September","Oktober","November","Desember"};

//menampilkan elemen array

for (int x=0;x<bulan.length;x++){

b.addItem(bulan[x]);
    


}
    }//GEN-LAST:event_formWindowActivated
 
                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proloker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proloker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proloker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proloker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proloker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JUR;
    private javax.swing.JTextField NM;
    private javax.swing.JTextField PT;
    private javax.swing.JTextField TTL;
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton aa;
    private javax.swing.JRadioButton aaa;
    private java.awt.Checkbox adm;
    private java.awt.Checkbox ak;
    private java.awt.Checkbox ap;
    private javax.swing.JComboBox<String> b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dp;
    private java.awt.Checkbox is;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Checkbox or;
    private javax.swing.JTextArea out;
    private java.awt.Checkbox sa;
    private java.awt.Checkbox sd;
    private java.awt.Checkbox sek;
    private javax.swing.JComboBox<String> t;
    private javax.swing.JComboBox<String> th;
    // End of variables declaration//GEN-END:variables

    private void isSelected() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
